float64             utc_time
float64             latitude
float64             longitude
float64             altitude
float64             heading

std_msgs/String     property_type
float64             measure

std_msgs/String     feature
std_msgs/String     process
std_msgs/String     parameter
std_msgs/String     result_quality

std_msgs/String     orchard_id
std_msgs/String     camera_id
std_msgs/String     secondary_camera_id
std_msgs/String     image_id
std_msgs/String     secondary_image_id

float64             ins_latitude
float64             ins_longitude
float64             ins_altitude
float64             ins_time
